CREATE TABLE IF NOT EXISTS person (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(30) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE, -- Increased for typical email lengths
    password VARCHAR(255) NOT NULL, -- Increased to accommodate hashed passwords
    role VARCHAR(30) NOT NULL,
    enable BOOLEAN NOT NULL DEFAULT false,
    provider VARCHAR(50), -- Added length
    provider_id VARCHAR(100) -- Added length
);


CREATE TABLE IF NOT EXISTS activation (
    person_email VARCHAR(100) REFERENCES person(email) ON DELETE CASCADE PRIMARY KEY,
    key VARCHAR NOT NULL UNIQUE
);

CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,  -- або VARCHAR(1000) залежно від потреб
    article VARCHAR(50) NOT NULL UNIQUE,
    price DECIMAL(10,2) CHECK (price > 0) NOT NULL,
    quantity INT CHECK (quantity >= 0) NOT NULL,
    category_id BIGINT REFERENCES category(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT current_timestamp
);

CREATE TABLE customer_order (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INT NOT NULL REFERENCES person(id) ON DELETE CASCADE,
    delivery_type VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    discount_percent INT NOT NULL DEFAULT 0,
    shipping_address VARCHAR(255),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE cart_item(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    person_id INT NOT NULL REFERENCES person(id) ON DELETE CASCADE,
    quantity INT CHECK (quantity > 0),
    order_id INT REFERENCES customer_order(id)
);